Voetbal/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Voetbal.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Voetbal/Controllers/WedstrijdController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

using Voetbal.Models;
using Voetbal.Service;

namespace Voetbal.Controllers
{
    public class WedstrijdController : Controller
    {
        WedstrijdService wedstrijdService;
        SpeeldagService speeldagService;
        public ActionResult Index()
        {
            speeldagService = new SpeeldagService();
            ViewBag.listSpeeldagen = new SelectList(speeldagService.All(), "Id", "Datum");
            return View();
        }

        [HttpPost]
        public ActionResult Index(int? Id)
        {
            if (Id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            wedstrijdService = new WedstrijdService();
            var listWedstrijden = wedstrijdService.WedstrijdBySpeeldag(Convert.ToInt16(Id));

            speeldagService = new SpeeldagService();
            ViewBag.listSpeeldagen = new SelectList(speeldagService.All(), "Id", "Id", "Id");

            return View(listWedstrijden);
        }
    }
}

Voetbal/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Voetbal/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Voetbal/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
@*Aurélien was hier*@

<div class="jumbotron">
    <h1>Belgian Soccer Tickets</h1>
    <p class="lead">Koop hier je tickets voor de mooiste westrijden van het belgische voetbal.</p>
</div>

<div class="row">
    <div class="col-md-12">
        <h2>Bekijk @Html.ActionLink("hier", "Index", "Wedstrijd") de wedstrijden en boek tot 10 tickets!</h2>
    </div>
</div>

Voetbal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Belgian Soccer Tickets", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Voetbal/Views/Shared/_WedstrijdView.cshtml
@model Voetbal.Models.Wedstrijd

    
<div id="game">
    <div class="row">
       <h3><strong>@Model.Speeldag.Datum</strong></h3>
    </div>
    <div class="row">
        <div class="col-md-6">
            <img src="~/Content/logos/@Model.Club1.Logo" />
        </div>
        <div class="col-md-6">
            <img src="~/Content/logos/@Model.Club.Logo" />
        </div>
    </div>
    <div class="row">
        <h4><strong>@Model.Stadion.Naam</strong></h4>
    </div>
    <p id="linkWedstrijd">@Html.ActionLink(Model.Club1.Naam + " - " + Model.Club.Naam + " --> Tickets", "Index", "Home")</p>
</div>

Voetbal/Views/Wedstrijd/Index.cshtml
@model IEnumerable<Voetbal.Models.Wedstrijd>

@{
    ViewBag.Title = "Index";
}

<h2>Kies hier uw wedstrijd.</h2>

@using (Html.BeginForm())
{
    <div class="form-horizontal">
        <div class="form-group">
            <div class="col-md-10">
                @Html.DropDownList("Id", ViewBag.listSpeeldagen as IEnumerable<SelectListItem>, "---Selecteer Speeldag ---", htmlAttributes: new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            <div classc="col-md-offset-2 col-md-10">
                <input type="submit" value="Toon Wedstrijden" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@if (Model != null)
{
    foreach (var item in Model)
    {
        
        @Html.Partial("~/Views/Shared/_WedstrijdView.cshtml", item)
    }
}